// AUTO-GENERATED by `pnpm db:types` from supabase/migrations. Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type AppRole = "customer" | "admin" | "staff" | "dispatcher" | "supplier";
export type ChatChannelKind = "whatsapp" | "instagram" | "messenger" | "telegram" | "phone";
export type DispatchStatus = "assigned" | "delivered" | "failed" | "reassigned";
export type OrderSource = "landing_page" | "checkout" | "quick_order";
export type OrderStatus = "awaiting_chat" | "in_chat" | "confirmed" | "dispatched" | "delivered" | "failed_delivery" | "returned" | "cancelled";
export type PaymentKind = "payment" | "refund";
export type PaymentMethod = "bank_transfer" | "pay_on_delivery" | "pos_on_delivery" | "other";
export type PaymentStatus = "unpaid" | "payment_claimed" | "paid" | "pay_on_delivery" | "part_paid" | "refunded";
export type ReviewStatus = "pending" | "approved" | "rejected";
export type SubmissionStatus = "draft" | "pending" | "approved" | "rejected";
export type SupplierStatus = "pending" | "approved" | "rejected" | "suspended";

export interface Tables {
  analytics_events: {
    Row: {
      id: number;
      event_name: string;
      event_id: string | null;
      session_id: string | null;
      order_id: string | null;
      product_id: string | null;
      landing_page_id: string | null;
      path: string | null;
      utm_source: string | null;
      utm_medium: string | null;
      utm_campaign: string | null;
      data: Json;
      created_at: string;
    };
    Insert: {
      id?: number;
      event_name: string;
      event_id?: string | null;
      session_id?: string | null;
      order_id?: string | null;
      product_id?: string | null;
      landing_page_id?: string | null;
      path?: string | null;
      utm_source?: string | null;
      utm_medium?: string | null;
      utm_campaign?: string | null;
      data?: Json;
      created_at?: string;
    };
  };
  audit_log: {
    Row: {
      id: number;
      actor_id: string | null;
      actor_role: string;
      action: string;
      entity: string;
      entity_id: string | null;
      data: Json;
      created_at: string;
    };
    Insert: {
      id?: number;
      actor_id?: string | null;
      actor_role?: string;
      action: string;
      entity: string;
      entity_id?: string | null;
      data?: Json;
      created_at?: string;
    };
  };
  bundles: {
    Row: {
      id: string;
      product_id: string;
      label: string;
      short_label: string | null;
      description: string | null;
      quantity: number;
      price_kobo: number;
      compare_at_kobo: number | null;
      tag: string | null;
      side_tag: string | null;
      note: string | null;
      is_popular: boolean;
      is_active: boolean;
      sort_order: number;
      created_at: string;
    };
    Insert: {
      id?: string;
      product_id: string;
      label: string;
      short_label?: string | null;
      description?: string | null;
      quantity: number;
      price_kobo: number;
      compare_at_kobo?: number | null;
      tag?: string | null;
      side_tag?: string | null;
      note?: string | null;
      is_popular?: boolean;
      is_active?: boolean;
      sort_order?: number;
      created_at?: string;
    };
  };
  carts: {
    Row: {
      id: string;
      user_id: string | null;
      anon_token: string | null;
      items: Json;
      updated_at: string;
    };
    Insert: {
      id?: string;
      user_id?: string | null;
      anon_token?: string | null;
      items?: Json;
      updated_at?: string;
    };
  };
  categories: {
    Row: {
      id: string;
      slug: string;
      name: string;
      short_name: string | null;
      emoji: string | null;
      icon: string;
      description: string | null;
      sort_order: number;
      is_active: boolean;
      created_at: string;
    };
    Insert: {
      id?: string;
      slug: string;
      name: string;
      short_name?: string | null;
      emoji?: string | null;
      icon?: string;
      description?: string | null;
      sort_order?: number;
      is_active?: boolean;
      created_at?: string;
    };
  };
  chat_channels: {
    Row: {
      id: string;
      kind: ChatChannelKind;
      label: string;
      handle: string;
      hub_code: string | null;
      weight: number;
      is_enabled: boolean;
      sort_order: number;
      created_at: string;
    };
    Insert: {
      id?: string;
      kind: ChatChannelKind;
      label: string;
      handle: string;
      hub_code?: string | null;
      weight?: number;
      is_enabled?: boolean;
      sort_order?: number;
      created_at?: string;
    };
  };
  customer_addresses: {
    Row: {
      id: string;
      user_id: string;
      label: string;
      full_name: string;
      phone_e164: string;
      state: string;
      city: string;
      address: string;
      landmark: string | null;
      is_default: boolean;
      created_at: string;
    };
    Insert: {
      id?: string;
      user_id: string;
      label?: string;
      full_name: string;
      phone_e164: string;
      state: string;
      city: string;
      address: string;
      landmark?: string | null;
      is_default?: boolean;
      created_at?: string;
    };
  };
  delivery_zones: {
    Row: {
      state: string;
      display_name: string;
      fee_kobo: number;
      eta_min_days: number;
      eta_max_days: number;
      same_day_enabled: boolean;
      hub_code: string;
      is_active: boolean;
      sort_order: number;
    };
    Insert: {
      state: string;
      display_name: string;
      fee_kobo: number;
      eta_min_days: number;
      eta_max_days: number;
      same_day_enabled?: boolean;
      hub_code: string;
      is_active?: boolean;
      sort_order?: number;
    };
  };
  dispatch_assignments: {
    Row: {
      id: string;
      order_id: string;
      dispatcher_id: string;
      assigned_by: string;
      status: DispatchStatus;
      collected_kobo: number;
      collected_method: PaymentMethod | null;
      failure_reason: string | null;
      proof_url: string | null;
      note: string | null;
      assigned_at: string;
      completed_at: string | null;
    };
    Insert: {
      id?: string;
      order_id: string;
      dispatcher_id: string;
      assigned_by: string;
      status?: DispatchStatus;
      collected_kobo?: number;
      collected_method?: PaymentMethod | null;
      failure_reason?: string | null;
      proof_url?: string | null;
      note?: string | null;
      assigned_at?: string;
      completed_at?: string | null;
    };
  };
  flash_deals: {
    Row: {
      id: string;
      product_id: string;
      title: string | null;
      promo_text: string | null;
      deal_price_kobo: number | null;
      starts_at: string;
      ends_at: string;
      is_active: boolean;
      sort_order: number;
      created_at: string;
    };
    Insert: {
      id?: string;
      product_id: string;
      title?: string | null;
      promo_text?: string | null;
      deal_price_kobo?: number | null;
      starts_at: string;
      ends_at: string;
      is_active?: boolean;
      sort_order?: number;
      created_at?: string;
    };
  };
  free_gifts: {
    Row: {
      id: string;
      product_id: string;
      name: string;
      value_kobo: number;
      image_url: string | null;
      conditions: string | null;
      min_order_kobo: number;
      is_active: boolean;
      created_at: string;
    };
    Insert: {
      id?: string;
      product_id: string;
      name: string;
      value_kobo?: number;
      image_url?: string | null;
      conditions?: string | null;
      min_order_kobo?: number;
      is_active?: boolean;
      created_at?: string;
    };
  };
  hubs: {
    Row: {
      id: string;
      code: string;
      name: string;
      city: string;
      state: string;
      is_fulfilment_fallback: boolean;
      is_active: boolean;
      sort_order: number;
    };
    Insert: {
      id?: string;
      code: string;
      name: string;
      city: string;
      state: string;
      is_fulfilment_fallback?: boolean;
      is_active?: boolean;
      sort_order?: number;
    };
  };
  inventory: {
    Row: {
      product_id: string;
      hub_id: string;
      on_hand: number;
      reserved: number;
      batch_size: number;
      low_stock_threshold: number;
      updated_at: string;
    };
    Insert: {
      product_id: string;
      hub_id: string;
      on_hand?: number;
      reserved?: number;
      batch_size?: number;
      low_stock_threshold?: number;
      updated_at?: string;
    };
  };
  inventory_movements: {
    Row: {
      id: number;
      product_id: string;
      hub_id: string;
      delta_on_hand: number;
      delta_reserved: number;
      reason: string;
      order_id: string | null;
      actor_id: string | null;
      created_at: string;
    };
    Insert: {
      id?: number;
      product_id: string;
      hub_id: string;
      delta_on_hand?: number;
      delta_reserved?: number;
      reason: string;
      order_id?: string | null;
      actor_id?: string | null;
      created_at?: string;
    };
  };
  landing_page_sections: {
    Row: {
      id: string;
      landing_page_id: string;
      kind: string;
      title: string | null;
      items: Json;
      body: string | null;
      sort_order: number;
      is_visible: boolean;
    };
    Insert: {
      id?: string;
      landing_page_id: string;
      kind: string;
      title?: string | null;
      items?: Json;
      body?: string | null;
      sort_order?: number;
      is_visible?: boolean;
    };
  };
  landing_pages: {
    Row: {
      id: string;
      slug: string;
      product_id: string;
      is_published: boolean;
      hook_label: string;
      hook_banner: string | null;
      trend_badge: string | null;
      headline: string;
      subheadline: string | null;
      hero_overlay_text: string | null;
      hero_overlay_icon: string | null;
      warranty_badge: string | null;
      regions_text: string | null;
      campaign_ends_at: string | null;
      features_title: string | null;
      features_subtitle: string | null;
      video_url: string | null;
      video_poster_url: string | null;
      video_title: string | null;
      video_subtitle: string | null;
      cta_label: string;
      seo_title: string | null;
      seo_description: string | null;
      og_image_url: string | null;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      slug: string;
      product_id: string;
      is_published?: boolean;
      hook_label?: string;
      hook_banner?: string | null;
      trend_badge?: string | null;
      headline: string;
      subheadline?: string | null;
      hero_overlay_text?: string | null;
      hero_overlay_icon?: string | null;
      warranty_badge?: string | null;
      regions_text?: string | null;
      campaign_ends_at?: string | null;
      features_title?: string | null;
      features_subtitle?: string | null;
      video_url?: string | null;
      video_poster_url?: string | null;
      video_title?: string | null;
      video_subtitle?: string | null;
      cta_label?: string;
      seo_title?: string | null;
      seo_description?: string | null;
      og_image_url?: string | null;
      created_at?: string;
      updated_at?: string;
    };
  };
  meta_events: {
    Row: {
      id: string;
      event_name: string;
      event_id: string;
      order_id: string | null;
      payload: Json;
      status: string;
      attempts: number;
      last_error: string | null;
      created_at: string;
      sent_at: string | null;
    };
    Insert: {
      id?: string;
      event_name: string;
      event_id: string;
      order_id?: string | null;
      payload?: Json;
      status?: string;
      attempts?: number;
      last_error?: string | null;
      created_at?: string;
      sent_at?: string | null;
    };
  };
  notifications_outbox: {
    Row: {
      id: string;
      channel: string;
      recipient: string;
      template: string;
      subject: string | null;
      body: string;
      order_id: string | null;
      status: string;
      provider_ref: string | null;
      error: string | null;
      created_at: string;
      sent_at: string | null;
    };
    Insert: {
      id?: string;
      channel: string;
      recipient: string;
      template: string;
      subject?: string | null;
      body: string;
      order_id?: string | null;
      status?: string;
      provider_ref?: string | null;
      error?: string | null;
      created_at?: string;
      sent_at?: string | null;
    };
  };
  order_events: {
    Row: {
      id: number;
      order_id: string;
      actor_id: string | null;
      actor_role: string;
      kind: string;
      from_status: string | null;
      to_status: string | null;
      note: string | null;
      data: Json;
      created_at: string;
    };
    Insert: {
      id?: number;
      order_id: string;
      actor_id?: string | null;
      actor_role?: string;
      kind: string;
      from_status?: string | null;
      to_status?: string | null;
      note?: string | null;
      data?: Json;
      created_at?: string;
    };
  };
  order_items: {
    Row: {
      id: string;
      order_id: string;
      product_id: string;
      bundle_id: string | null;
      gift_id: string | null;
      name: string;
      bundle_label: string | null;
      image_url: string | null;
      packs: number;
      units: number;
      unit_price_kobo: number;
      line_total_kobo: number;
      is_free_gift: boolean;
    };
    Insert: {
      id?: string;
      order_id: string;
      product_id: string;
      bundle_id?: string | null;
      gift_id?: string | null;
      name: string;
      bundle_label?: string | null;
      image_url?: string | null;
      packs?: number;
      units: number;
      unit_price_kobo: number;
      line_total_kobo: number;
      is_free_gift?: boolean;
    };
  };
  orders: {
    Row: {
      id: string;
      order_number: string;
      public_token: string;
      idempotency_key: string | null;
      user_id: string | null;
      status: OrderStatus;
      payment_status: PaymentStatus;
      source: OrderSource;
      landing_page_id: string | null;
      customer_name: string;
      phone_e164: string;
      alt_phone_e164: string | null;
      email: string | null;
      state: string;
      city: string;
      address: string;
      landmark: string | null;
      customer_note: string | null;
      hub_id: string;
      subtotal_kobo: number;
      delivery_fee_kobo: number;
      discount_kobo: number;
      total_kobo: number;
      amount_paid_kobo: number;
      is_overpaid: boolean | null;
      same_day: boolean;
      eta_min_days: number;
      eta_max_days: number;
      chat_channel: ChatChannelKind;
      chat_channel_id: string | null;
      chat_number: string | null;
      chat_clicked_at: string | null;
      is_duplicate_suspect: boolean;
      duplicate_of: string | null;
      utm_source: string | null;
      utm_medium: string | null;
      utm_campaign: string | null;
      utm_content: string | null;
      utm_term: string | null;
      fbclid: string | null;
      fbc: string | null;
      fbp: string | null;
      client_ip_hash: string | null;
      user_agent: string | null;
      first_response_at: string | null;
      confirmed_at: string | null;
      dispatched_at: string | null;
      delivered_at: string | null;
      cancelled_at: string | null;
      paid_at: string | null;
      created_at: string;
      updated_at: string;
      pod_agreed: boolean;
    };
    Insert: {
      id?: string;
      order_number: string;
      public_token?: string;
      idempotency_key?: string | null;
      user_id?: string | null;
      status?: OrderStatus;
      payment_status?: PaymentStatus;
      source?: OrderSource;
      landing_page_id?: string | null;
      customer_name: string;
      phone_e164: string;
      alt_phone_e164?: string | null;
      email?: string | null;
      state: string;
      city: string;
      address: string;
      landmark?: string | null;
      customer_note?: string | null;
      hub_id: string;
      subtotal_kobo: number;
      delivery_fee_kobo: number;
      discount_kobo?: number;
      total_kobo: number;
      amount_paid_kobo?: number;
      same_day?: boolean;
      eta_min_days: number;
      eta_max_days: number;
      chat_channel?: ChatChannelKind;
      chat_channel_id?: string | null;
      chat_number?: string | null;
      chat_clicked_at?: string | null;
      is_duplicate_suspect?: boolean;
      duplicate_of?: string | null;
      utm_source?: string | null;
      utm_medium?: string | null;
      utm_campaign?: string | null;
      utm_content?: string | null;
      utm_term?: string | null;
      fbclid?: string | null;
      fbc?: string | null;
      fbp?: string | null;
      client_ip_hash?: string | null;
      user_agent?: string | null;
      first_response_at?: string | null;
      confirmed_at?: string | null;
      dispatched_at?: string | null;
      delivered_at?: string | null;
      cancelled_at?: string | null;
      paid_at?: string | null;
      created_at?: string;
      updated_at?: string;
      pod_agreed?: boolean;
    };
  };
  payments: {
    Row: {
      id: string;
      order_id: string;
      kind: PaymentKind;
      amount_kobo: number;
      method: PaymentMethod;
      reference: string | null;
      note: string | null;
      proof_url: string | null;
      recorded_by: string;
      recorded_by_role: string;
      verified_at: string;
      created_at: string;
    };
    Insert: {
      id?: string;
      order_id: string;
      kind?: PaymentKind;
      amount_kobo: number;
      method: PaymentMethod;
      reference?: string | null;
      note?: string | null;
      proof_url?: string | null;
      recorded_by: string;
      recorded_by_role: string;
      verified_at?: string;
      created_at?: string;
    };
  };
  product_faqs: {
    Row: {
      id: string;
      product_id: string;
      question: string;
      answer: string;
      sort_order: number;
    };
    Insert: {
      id?: string;
      product_id: string;
      question: string;
      answer: string;
      sort_order?: number;
    };
  };
  product_features: {
    Row: {
      id: string;
      product_id: string;
      icon: string;
      title: string;
      description: string;
      sort_order: number;
    };
    Insert: {
      id?: string;
      product_id: string;
      icon?: string;
      title: string;
      description: string;
      sort_order?: number;
    };
  };
  product_images: {
    Row: {
      id: string;
      product_id: string;
      url: string;
      alt: string;
      sort_order: number;
      created_at: string;
    };
    Insert: {
      id?: string;
      product_id: string;
      url: string;
      alt?: string;
      sort_order?: number;
      created_at?: string;
    };
  };
  products: {
    Row: {
      id: string;
      slug: string;
      name: string;
      short_description: string | null;
      description: string | null;
      category_id: string | null;
      supplier_id: string | null;
      price_kobo: number;
      compare_at_kobo: number | null;
      sku: string | null;
      tags: string[];
      image_badge: string | null;
      image_badge_style: string;
      image_badge_icon: string | null;
      perk_text: string | null;
      perk_icon: string | null;
      perk_style: string;
      delivery_note: string | null;
      delivery_note_icon: string | null;
      pod_available: boolean;
      warranty_months: number;
      specs: Json;
      is_active: boolean;
      curated_rank: number | null;
      curated_label: string | null;
      seo_title: string | null;
      seo_description: string | null;
      rating_avg: number;
      review_count: number;
      sold_count: number;
      search_vector: string | null;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      slug: string;
      name: string;
      short_description?: string | null;
      description?: string | null;
      category_id?: string | null;
      supplier_id?: string | null;
      price_kobo: number;
      compare_at_kobo?: number | null;
      sku?: string | null;
      tags?: string[];
      image_badge?: string | null;
      image_badge_style?: string;
      image_badge_icon?: string | null;
      perk_text?: string | null;
      perk_icon?: string | null;
      perk_style?: string;
      delivery_note?: string | null;
      delivery_note_icon?: string | null;
      pod_available?: boolean;
      warranty_months?: number;
      specs?: Json;
      is_active?: boolean;
      curated_rank?: number | null;
      curated_label?: string | null;
      seo_title?: string | null;
      seo_description?: string | null;
      rating_avg?: number;
      review_count?: number;
      sold_count?: number;
      created_at?: string;
      updated_at?: string;
    };
  };
  profiles: {
    Row: {
      id: string;
      role: AppRole;
      full_name: string | null;
      phone: string | null;
      email: string | null;
      is_active: boolean;
      hub_code: string | null;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id: string;
      role?: AppRole;
      full_name?: string | null;
      phone?: string | null;
      email?: string | null;
      is_active?: boolean;
      hub_code?: string | null;
      created_at?: string;
      updated_at?: string;
    };
  };
  rate_limits: {
    Row: {
      key: string;
      window_start: string;
      hits: number;
    };
    Insert: {
      key: string;
      window_start: string;
      hits?: number;
    };
  };
  reviews: {
    Row: {
      id: string;
      product_id: string;
      user_id: string | null;
      order_id: string | null;
      author_name: string;
      location: string | null;
      rating: number;
      body: string;
      status: ReviewStatus;
      is_verified_purchase: boolean;
      is_sample: boolean;
      created_at: string;
    };
    Insert: {
      id?: string;
      product_id: string;
      user_id?: string | null;
      order_id?: string | null;
      author_name: string;
      location?: string | null;
      rating: number;
      body: string;
      status?: ReviewStatus;
      is_verified_purchase?: boolean;
      is_sample?: boolean;
      created_at?: string;
    };
  };
  settings: {
    Row: {
      key: string;
      value: Json;
      is_public: boolean;
      description: string | null;
      updated_at: string;
      updated_by: string | null;
    };
    Insert: {
      key: string;
      value: Json;
      is_public?: boolean;
      description?: string | null;
      updated_at?: string;
      updated_by?: string | null;
    };
  };
  supplier_products: {
    Row: {
      id: string;
      supplier_id: string;
      name: string;
      description: string;
      category_id: string | null;
      proposed_price_kobo: number;
      compare_at_kobo: number | null;
      image_urls: string[];
      stock_available: number;
      status: SubmissionStatus;
      review_note: string | null;
      reviewed_by: string | null;
      reviewed_at: string | null;
      product_id: string | null;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      supplier_id: string;
      name: string;
      description: string;
      category_id?: string | null;
      proposed_price_kobo: number;
      compare_at_kobo?: number | null;
      image_urls?: string[];
      stock_available?: number;
      status?: SubmissionStatus;
      review_note?: string | null;
      reviewed_by?: string | null;
      reviewed_at?: string | null;
      product_id?: string | null;
      created_at?: string;
      updated_at?: string;
    };
  };
  suppliers: {
    Row: {
      id: string;
      user_id: string | null;
      business_name: string;
      contact_name: string;
      phone_e164: string;
      email: string;
      cac_number: string | null;
      categories: string[];
      sample_links: string[];
      sample_photo_urls: string[];
      message: string | null;
      status: SupplierStatus;
      review_note: string | null;
      reviewed_by: string | null;
      reviewed_at: string | null;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      user_id?: string | null;
      business_name: string;
      contact_name: string;
      phone_e164: string;
      email: string;
      cac_number?: string | null;
      categories?: string[];
      sample_links?: string[];
      sample_photo_urls?: string[];
      message?: string | null;
      status?: SupplierStatus;
      review_note?: string | null;
      reviewed_by?: string | null;
      reviewed_at?: string | null;
      created_at?: string;
      updated_at?: string;
    };
  };
  wishlists: {
    Row: {
      user_id: string;
      product_id: string;
      created_at: string;
    };
    Insert: {
      user_id: string;
      product_id: string;
      created_at?: string;
    };
  };
}

export type Row<T extends keyof Tables> = Tables[T]["Row"];
export type Insert<T extends keyof Tables> = Tables[T]["Insert"];
