// Generates src/server/db/types.ts from the migrated schema (information_schema introspection).
import { writeFileSync } from "node:fs";
import path from "node:path";
import { openLocalDb } from "../src/server/db/core";

const db = await openLocalDb("memory", { seed: false });

const enums = await db.query<{ name: string; values: string[] }>(`
  select t.typname as name, array_agg(e.enumlabel order by e.enumsortorder) as values
    from pg_type t join pg_enum e on e.enumtypid = t.oid join pg_namespace n on n.oid = t.typnamespace
   where n.nspname = 'public' group by t.typname order by t.typname`);

const cols = await db.query<{
  table_name: string;
  column_name: string;
  data_type: string;
  udt_name: string;
  is_nullable: string;
  column_default: string | null;
  is_generated: string;
  is_identity: string;
}>(`
  select c.table_name, c.column_name, c.data_type, c.udt_name, c.is_nullable, c.column_default, c.is_generated, c.is_identity
    from information_schema.columns c
    join information_schema.tables t on t.table_name = c.table_name and t.table_schema = c.table_schema
   where c.table_schema = 'public' and t.table_type = 'BASE TABLE'
   order by c.table_name, c.ordinal_position`);
await db.close();

const enumNames = new Set(enums.map((e) => e.name));
const pascal = (s: string) => s.replace(/(^|_)([a-z])/g, (_, __, c: string) => c.toUpperCase());

function tsType(c: (typeof cols)[number]): string {
  const u = c.udt_name;
  if (enumNames.has(u)) return pascal(u);
  if (u.startsWith("_")) {
    const inner = u.slice(1);
    return `${enumNames.has(inner) ? pascal(inner) : scalar(inner)}[]`;
  }
  return scalar(u);
}
function scalar(u: string): string {
  if (["int2", "int4", "int8", "float4", "float8", "numeric"].includes(u)) return "number";
  if (u === "bool") return "boolean";
  if (u === "json" || u === "jsonb") return "Json";
  return "string"; // text, uuid, timestamptz, tsvector, date, time
}

const tables = new Map<string, typeof cols>();
for (const c of cols) tables.set(c.table_name, [...(tables.get(c.table_name) ?? []), c]);

let out = `// AUTO-GENERATED by \`pnpm db:types\` from supabase/migrations. Do not edit by hand.\n\n`;
out += `export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\n\n`;
for (const e of enums) out += `export type ${pascal(e.name)} = ${e.values.map((v) => JSON.stringify(v)).join(" | ")};\n`;
out += `\nexport interface Tables {\n`;
for (const [table, columns] of tables) {
  out += `  ${table}: {\n    Row: {\n`;
  for (const c of columns) out += `      ${c.column_name}: ${tsType(c)}${c.is_nullable === "YES" ? " | null" : ""};\n`;
  out += `    };\n    Insert: {\n`;
  for (const c of columns) {
    if (c.is_generated === "ALWAYS") continue;
    const optional = c.is_nullable === "YES" || c.column_default !== null || c.is_identity === "YES";
    out += `      ${c.column_name}${optional ? "?" : ""}: ${tsType(c)}${c.is_nullable === "YES" ? " | null" : ""};\n`;
  }
  out += `    };\n  };\n`;
}
out += `}\n\nexport type Row<T extends keyof Tables> = Tables[T]["Row"];\nexport type Insert<T extends keyof Tables> = Tables[T]["Insert"];\n`;

const target = path.join(process.cwd(), "src", "server", "db", "types.ts");
writeFileSync(target, out);
console.log(`Wrote ${target} (${tables.size} tables, ${enums.length} enums)`);
