// Generates src/components/icons/paths.ts with only the Material Symbols (Outlined, weight 400)
// icons the app uses, as inline SVG path data. Avoids shipping the >1MB icon font.
// Usage: node scripts/gen-icons.mjs   (add names to ICONS below; "-fill" suffix = filled variant)
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";

const ICONS = [
  "verified_user", "search", "chat", "shopping_bag", "local_fire_department", "tune", "restart_alt", "bolt",
  "arrow_forward", "arrow_back", "chevron_right", "chevron_left", "devices", "skillet", "directions_car", "solar_power",
  "build", "shield", "flash_on", "star", "star-fill", "shopping_cart_checkout", "local_shipping", "payments",
  "verified", "verified-fill", "check_circle", "check_circle-fill", "handshake", "speed", "fact_check", "lock",
  "support_agent", "storefront", "grid_view", "sell", "favorite", "favorite-fill", "schedule",
  "redeem", "workspace_premium", "battery_charging_full", "security", "autorenew", "currency_exchange", "arrow_back_ios_new",
  "share", "trending_up", "location_on", "shield_with_heart", "electric_meter", "timer", "warning", "inventory_2",
  "tornado", "air", "water_drop", "sports_volleyball", "play_arrow-fill", "rocket_launch", "person", "call",
  "phone_iphone", "map", "home_pin", "report", "expand_more", "task_alt", "home", "category", "close", "add",
  "remove", "delete", "content_copy", "open_in_new", "mail", "menu", "logout", "login", "edit", "visibility",
  "upload", "image", "receipt_long", "dashboard", "inventory", "group", "two_wheeler", "loyalty", "campaign",
  "rate_review", "settings", "history", "analytics", "account_circle", "sensors", "bedtime", "usb", "check", "info",
  "error", "filter_list", "sort", "download", "print", "notifications", "store", "badge", "done_all", "cancel",
  "add_photo_alternate", "navigation", "photo_camera", "speed", "bookmark", "chat_bubble", "send", "forum",
  "local_mall", "inventory", "pending", "hourglass_top", "price_check", "account_balance", "public", "language",
  "help", "policy", "gavel", "undo", "refresh", "visibility_off", "key", "qr_code_2", "sms", "touch_app",
  "play_arrow-fill", "play_arrow", "receipt", "package_2", "radio_button_unchecked",
];

const unique = [...new Set(ICONS)];
const cacheDir = path.join(process.cwd(), ".data", "icon-cache");
mkdirSync(cacheDir, { recursive: true });

async function fetchSvg(name) {
  const file = path.join(cacheDir, `${name}.svg`);
  if (existsSync(file)) return readFileSync(file, "utf8");
  const url = `https://cdn.jsdelivr.net/npm/@material-symbols/svg-400@latest/outlined/${name}.svg`;
  for (let attempt = 0; attempt < 4; attempt++) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(60_000) });
      if (res.status === 404) throw new Error(`Unknown icon: ${name}`);
      if (!res.ok) throw new Error(`${res.status}`);
      const text = await res.text();
      writeFileSync(file, text);
      return text;
    } catch (e) {
      if (String(e).includes("Unknown icon")) throw e;
      if (attempt === 3) throw e;
    }
  }
}

const entries = [];
const missing = [];
const queue = [...unique];
const workers = Array.from({ length: 8 }, async () => {
  while (queue.length) {
    const name = queue.shift();
    let svg;
    try {
      svg = await fetchSvg(name);
    } catch {
      missing.push(name);
      continue;
    }
    const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
    if (!paths.length) throw new Error(`No path in ${name}`);
    entries.push([name, paths.join(" ")]);
  }
});
await Promise.all(workers);
entries.sort((a, b) => a[0].localeCompare(b[0]));

const out = `// AUTO-GENERATED by \`node scripts/gen-icons.mjs\` — Material Symbols Outlined (Apache-2.0), weight 400.
// viewBox "0 -960 960 960". Add icons in scripts/gen-icons.mjs, never by hand.
export const ICON_PATHS = {
${entries.map(([n, d]) => `  ${JSON.stringify(n)}: ${JSON.stringify(d)},`).join("\n")}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`;
const target = path.join(process.cwd(), "src", "components", "icons", "paths.ts");
mkdirSync(path.dirname(target), { recursive: true });
writeFileSync(target, out);

// SVG sprite used by <Icon> at runtime, so icon data never ships in JavaScript bundles.
const sprite = `<svg xmlns="http://www.w3.org/2000/svg">${entries
  .map(([n, d]) => `<symbol id="${n}" viewBox="0 -960 960 960"><path d="${d}"/></symbol>`)
  .join("")}</svg>`;
writeFileSync(path.join(process.cwd(), "public", "icons.svg"), sprite);
const version = createHash("sha1").update(sprite).digest("hex").slice(0, 8);
writeFileSync(
  path.join(process.cwd(), "src", "components", "icons", "names.ts"),
  `// AUTO-GENERATED by \`node scripts/gen-icons.mjs\`. Names available in public/icons.svg.
export const ICON_SPRITE_URL = "/icons.svg?v=${version}";

/** Base names that have a "-fill" variant in the sprite. */
export const FILLED_ICONS: ReadonlySet<string> = new Set(${JSON.stringify(
    entries.filter(([n]) => n.endsWith("-fill")).map(([n]) => n.slice(0, -5)),
  )});

export type IconName =
${entries.map(([n]) => `  | ${JSON.stringify(n)}`).join("\n")};
`,
);
console.log(`Wrote ${entries.length} icons to ${target}`);
if (missing.length) {
  console.error(`Missing icons: ${missing.join(", ")}`);
  process.exitCode = 1;
}
