/**
 * Seed catalogue. Prices are written in whole naira here for readability and converted to kobo
 * by the seed builder. Every product shown in /design is included with its design copy and price.
 * Images under /images/products/*.webp: design photos where the mock had one, otherwise branded
 * placeholders (generated by `pnpm brand`) that the admin should replace with real photos.
 */

export interface SeedCategory {
  slug: string;
  name: string;
  shortName: string;
  emoji: string;
  icon: string;
  description: string;
}

export const CATEGORIES: SeedCategory[] = [
  { slug: "smart-gadgets", name: "Smart Gadgets", shortName: "Gadgets", emoji: "📱", icon: "devices", description: "Clever everyday tech that simply works." },
  { slug: "kitchen", name: "Kitchen Hacks", shortName: "Kitchen Tools", emoji: "🍳", icon: "skillet", description: "Save time on soups, stews and prep." },
  { slug: "car-tech", name: "Car Tech", shortName: "Car Gadgets", emoji: "🚗", icon: "directions_car", description: "Keep your car clean, charged and road-ready." },
  { slug: "solar-power", name: "Solar & Power", shortName: "Power & Solar", emoji: "⚡", icon: "solar_power", description: "Beat NEPA with solar and backup power." },
  { slug: "problem-solvers", name: "Problem Solvers", shortName: "Problem Solvers", emoji: "🔧", icon: "build", description: "Viral life hacks for everyday wahala." },
  { slug: "security", name: "Security Tech", shortName: "Security", emoji: "🛡️", icon: "shield", description: "Protect your home, car and valuables." },
  { slug: "home-tech", name: "Home Tech", shortName: "Home Tech", emoji: "🏠", icon: "home", description: "Small upgrades for a smarter home." },
];

export interface SeedFeature {
  icon: string;
  title: string;
  description: string;
}
export interface SeedFaq {
  q: string;
  a: string;
}
export interface SeedBundle {
  key: string;
  label: string;
  shortLabel: string;
  description: string;
  quantity: number;
  /** Regular price (₦). */
  price: number;
  /** Promo price (₦), charged only until the seed promo deadline (PROMO_ENDS_AT in index.ts). */
  promo?: number;
  compareAt: number | null;
  tag?: string;
  sideTag?: string;
  note?: string;
  popular?: boolean;
}
export interface SeedGift {
  name: string;
  value: number;
  image?: string;
  conditions: string;
  /** Gift is part of the promo and stops at the promo deadline. */
  endsWithPromo?: boolean;
}
export interface SeedProduct {
  slug: string;
  name: string;
  category: string;
  price: number;
  compareAt: number | null;
  short: string;
  description: string;
  images: { file: string; alt: string }[];
  tags: string[];
  imageBadge?: { text: string; style: "navy" | "emerald" | "gold" | "bronze" | "red"; icon: string };
  perk?: { text: string; icon: string; style: "gold" | "neutral" };
  deliveryNote?: { text: string; icon: string };
  curated?: { rank: number; label: string };
  podAvailable?: boolean;
  warrantyMonths?: number;
  specs?: { label: string; value: string }[];
  features?: SeedFeature[];
  faqs?: SeedFaq[];
  bundles?: SeedBundle[];
  gift?: SeedGift;
  /** Flash deal (₦ price) ending at the promo deadline. */
  flash?: { price: number; title: string; promoText: string | null; sort: number };
  /** units per hub: [lagos, abuja, warehouse]; batch = units received in the current batch (admin data, not shown) */
  stock: [number, number, number];
  batch?: [number, number, number];
  ageDays: number; // for "Newest" sort
}

const img = (file: string, alt: string) => ({ file, alt });
const ph = (slug: string, alt: string) => img(`ph-${slug}.webp`, alt);

export const PRODUCTS: SeedProduct[] = [
  // ── From the Ad Landing Page + Home flash deals ────────────────────────────
  {
    slug: "turbo-car-vacuum",
    name: "4-in-1 Turbo Cordless Car Vacuum & Blower",
    category: "car-tech",
    price: 24_500,
    compareAt: null,
    short: "Vacuum, blow, inflate & deflate — 9,000Pa cordless jet power for car and home.",
    description:
      "Blow stubborn AC sand, pull deep coin crumbs and inflate car tyres in 60 seconds with the MUBAZZAR 4-in-1 Turbo Cordless Handheld Jet Vacuum. Built for dusty harmattan seasons, roadside sand and everyday quick interior touch-ups.",
    images: [
      img("car-vacuum-hero.webp", "MUBAZZAR 4-in-1 cordless handheld car vacuum suctioning sand and crumbs from leather car seats"),
      img("car-vacuum-1.webp", "Handheld cordless vacuum cleaning crumbs and fine red sand from an SUV floor mat"),
      img("car-vacuum-2.webp", "Reverse blow nozzle blasting dust out of a car AC dashboard vent"),
      img("car-vacuum-3.webp", "Turbo blower inflating a swimming float with the cone nozzle"),
      img("car-vacuum-4.webp", "Washable steel and HEPA double filter rinsed under running tap water"),
      img("car-vacuum-5.webp", "Unboxed package: navy box, Type-C cable, 4 nozzle heads, extra HEPA filter and pouch"),
    ],
    tags: ["vacuum", "car", "blower", "inflator", "cordless", "cleaning"],
    imageBadge: { text: "9,000Pa Suction", style: "navy", icon: "tornado" },
    deliveryNote: { text: "Lagos 24h Delivery", icon: "local_shipping" },
    warrantyMonths: 12,
    specs: [
      { label: "Suction power", value: "9,000Pa turbo vortex" },
      { label: "Battery", value: "Dual 2,000mAh lithium cells" },
      { label: "Runtime", value: "Up to 45 minutes" },
      { label: "Charging", value: "USB Type-C, ~2 hours" },
      { label: "Filter", value: "Washable dual HEPA" },
      { label: "Modes", value: "Vacuum · Blow · Inflate · Deflate" },
    ],
    features: [
      { icon: "tornado", title: "Extreme 9,000Pa Suction Power", description: "Lifts heavy coins, spilled groundnuts, pet hair, and coarse street sand trapped deep inside carpet fibers effortlessly." },
      { icon: "air", title: "Reverse High-Pressure Blower", description: "Flip it over to blast hidden dust from deep AC vents, steering column crevices, laptop keyboards, or light your weekend BBQ grill." },
      { icon: "battery_charging_full", title: "Heavy-Duty Type-C Fast Charging", description: "Dual 2,000mAh lithium cells give 45 minutes of continuous cordless cleaning. Power it up directly from your car cigarette lighter adapter or powerbank." },
      { icon: "water_drop", title: "Washable Dual HEPA Filter", description: "No costly refills. Simply rinse with tap water, dry, and snap back. Captures 99.9% of micro dust mites and allergens." },
      { icon: "sports_volleyball", title: "Inflator & Deflator Pump Mode", description: "Includes custom nozzles to pump party balloons, swimming rings, and air mattresses, or vacuum-seal storage bags for luggage space." },
    ],
    faqs: [
      { q: "How long does delivery take to my state?", a: "Orders within Lagos and Abuja placed before the daily cut-off can arrive the same day; otherwise next day. Port Harcourt, Ibadan, Benin, Kano, Enugu and all other states take 2 to 4 working days via our partner dispatch fleet. Your exact fee and ETA show in the order form when you pick your state." },
      { q: "Can I really open and check it before paying?", a: "Yes. If you agree Pay on Delivery with our team on WhatsApp, you can unseal the outer carton and switch the vacuum on to feel the suction and blower power before paying the rider by cash, POS or transfer." },
      { q: "What is inside the complete package?", a: "Every set includes: 1x MUBAZZAR 4-in-1 Turbo Handheld Device, 1x long flat crevice nozzle, 1x brush head for seat carpets, 1x reverse air-blow jet tip, 1x air inflator nozzle, 1x washable HEPA filter (plus an extra free bonus filter), 1x Type-C charging cable, user manual, plus your free Aromatherapy Car Diffuser while the promo runs." },
      { q: "How do I charge it? Can I use my car charger?", a: "Yes. It has a universal Type-C port, so you can charge it from your car USB port/adapter, any phone charger or a power bank. A full charge takes about 2 hours and lasts up to 45 minutes of cleaning." },
    ],
    bundles: [
      { key: "1x", label: "1x Turbo Vacuum Set", shortLabel: "1x Turbo Car Vacuum", description: "Vacuum + 4 nozzles + 1 extra HEPA filter", quantity: 1, price: 24_500, promo: 19_500, compareAt: null },
      { key: "2x", label: "2x Turbo Vacuum Sets (His & Hers)", shortLabel: "2x Turbo Car Vacuum (His & Hers)", description: "2 Vacuums + 2 Extra HEPA Filters", quantity: 2, price: 45_000, promo: 35_000, compareAt: null, tag: "MOST POPULAR", note: "Perfect for 2 cars or 1 for Car + 1 for Home", popular: true },
      { key: "3x", label: "3x Turbo Family Pack", shortLabel: "3x Turbo Car Vacuum (Family Pack)", description: "3 Vacuums + 3 Filters + Premium Tyre Gauge", quantity: 3, price: 63_000, promo: 49_000, compareAt: null, sideTag: "Best Value" },
    ],
    gift: { name: "Luxury Aromatherapy Car Diffuser", value: 4_500, image: "gift-diffuser.webp", conditions: "Packed free inside every vacuum order while this promo runs.", endsWithPromo: true },
    flash: { price: 19_500, title: "Car Vacuum Flash Deal", promoText: "+ FREE Extra HEPA Filter", sort: 1 },
    stock: [9, 25, 120],
    batch: [100, 60, 150],
    ageDays: 20,
  },
  {
    slug: "magnetic-solar-wall-light",
    name: "360° Rotatable Magnetic Solar Wall Light",
    category: "solar-power",
    price: 17_000,
    compareAt: null,
    short: "Motion-sensor solar security light that rotates 360° — no wiring, no NEPA bill.",
    description:
      "A waterproof solar wall light with a powerful motion sensor and magnetic 360° rotating head. Mount it on any wall, gate or fence and light up dark corners all night without electricity.",
    images: [img("solar-wall-light.webp", "360 degree rotatable magnetic solar wall light glowing on a brick wall at dusk")],
    tags: ["solar", "light", "security", "outdoor", "motion sensor"],
    imageBadge: { text: "Rainy-Season Proof", style: "navy", icon: "water_drop" },
    perk: { text: "No Wiring Needed", icon: "build", style: "neutral" },
    deliveryNote: { text: "Pay on Delivery", icon: "payments" },
    warrantyMonths: 6,
    specs: [
      { label: "Panel", value: "Monocrystalline solar" },
      { label: "Rating", value: "IP65 waterproof" },
      { label: "Modes", value: "Motion · Dim + motion · Always on" },
    ],
    features: [
      { icon: "solar_power", title: "Charges all day, shines all night", description: "High-efficiency panel stores enough sun for 10–12 hours of light." },
      { icon: "sensors", title: "Sensitive motion sensor", description: "Brightens instantly when someone approaches your gate or wall." },
      { icon: "water_drop", title: "Survives heavy downpours", description: "IP65 sealed body made for the Nigerian rainy season." },
    ],
    bundles: [
      { key: "1x", label: "1x Solar Wall Light", shortLabel: "1x Solar Wall Light", description: "Single light with mounting kit", quantity: 1, price: 17_000, promo: 14_000, compareAt: null },
      { key: "2x", label: "2x Solar Wall Lights", shortLabel: "2x Solar Wall Light", description: "Light up front gate and backyard", quantity: 2, price: 32_000, promo: 26_000, compareAt: null, tag: "MOST POPULAR", popular: true },
      { key: "4x", label: "4x Solar Wall Lights (Compound Pack)", shortLabel: "4x Solar Wall Light", description: "Cover all four corners of your compound", quantity: 4, price: 58_000, promo: 48_000, compareAt: null, sideTag: "Best Value" },
    ],
    flash: { price: 14_000, title: "Solar Light Flash Deal", promoText: null, sort: 2 },
    stock: [40, 30, 200],
    ageDays: 35,
  },
  // ── Home: Viral Problem Solvers ────────────────────────────────────────────
  {
    slug: "smart-anti-snore-device",
    name: "Smart Anti-Snore Micro Device",
    category: "smart-gadgets",
    price: 16_000,
    compareAt: 28_000,
    short: "Gentle pulse tech for quiet, restful sleep.",
    description: "A tiny, rechargeable under-chin device that senses snoring and sends gentle micro-pulses to help you change position — without waking you.",
    images: [img("anti-snore.webp", "Ergonomic smart anti-snore device on a bedside table")],
    tags: ["sleep", "snoring", "health", "smart"],
    curated: { rank: 1, label: "TOP VIRAL" },
    deliveryNote: { text: "Lagos 24h Delivery", icon: "local_shipping" },
    warrantyMonths: 6,
    features: [
      { icon: "bedtime", title: "Quiet nights again", description: "Detects snoring and responds with gentle pulses you barely feel." },
      { icon: "battery_charging_full", title: "Rechargeable", description: "One charge lasts about a week of nights." },
    ],
    stock: [30, 20, 80],
    ageDays: 12,
  },
  {
    slug: "electric-veggie-chopper",
    name: "Rechargeable Electric Veggie Chopper",
    category: "kitchen",
    price: 12_500,
    compareAt: 22_000,
    short: "Chop peppers, ginger & garlic in 5 seconds.",
    description: "Cordless mini food chopper with stainless steel blades. Perfect for pepper, onions, ginger, garlic and crayfish — clean up in seconds.",
    images: [img("veggie-chopper.webp", "Cordless electric vegetable chopper chopping chilli and onions on a kitchen counter")],
    tags: ["kitchen", "chopper", "pepper", "blender", "rechargeable"],
    curated: { rank: 2, label: "KITCHEN" },
    deliveryNote: { text: "Pay on Delivery", icon: "payments" },
    warrantyMonths: 6,
    features: [
      { icon: "skillet", title: "Soup prep in seconds", description: "Grinds pepper and onions for stew without tears." },
      { icon: "usb", title: "USB rechargeable", description: "Charge with any phone charger; 40+ uses per charge." },
    ],
    bundles: [
      { key: "1x", label: "1x Veggie Chopper", shortLabel: "1x Veggie Chopper", description: "250ml bowl + 3 blades", quantity: 1, price: 12_500, compareAt: 22_000 },
      { key: "2x", label: "2x Veggie Choppers (Gift Pack)", shortLabel: "2x Veggie Chopper", description: "One for you, one for Mama", quantity: 2, price: 23_000, compareAt: 44_000, tag: "MOST POPULAR", popular: true },
    ],
    stock: [50, 35, 150],
    ageDays: 40,
  },
  {
    slug: "slim-solar-powerbank-20000",
    name: "Ultra-Slim 20,000mAh Solar Powerbank",
    category: "solar-power",
    price: 24_000,
    compareAt: 40_000,
    short: "Inbuilt 4 cables: Type-C, Lightning, Micro.",
    description: "High-capacity slim power bank with a built-in solar panel, emergency torch and four built-in cables so you never carry a cord again.",
    images: [img("solar-powerbank.webp", "Ultra slim solar power bank with built-in cables on an outdoor desk")],
    tags: ["powerbank", "solar", "charger", "phone"],
    curated: { rank: 3, label: "ESSENTIAL" },
    deliveryNote: { text: "1-Year Guarantee", icon: "verified" },
    warrantyMonths: 12,
    specs: [
      { label: "Capacity", value: "20,000mAh" },
      { label: "Cables", value: "Type-C, Lightning, Micro-USB, USB-A" },
    ],
    stock: [35, 25, 140],
    ageDays: 60,
  },
  // ── Shop Catalog design grid ───────────────────────────────────────────────
  {
    slug: "retractable-car-charger-3in1",
    name: "High-Speed 3-in-1 Retractable Car Charger & Voltage Display",
    category: "car-tech",
    price: 11_500,
    compareAt: 18_000,
    short: "Three retractable cables and a live battery voltage display.",
    description: "Charge three phones at once from your cigarette lighter socket with retractable Type-C, Lightning and Micro cables, plus a digital voltmeter that warns you about a weak car battery.",
    images: [img("car-charger.webp", "3-in-1 retractable car charger with glowing voltage display in a car console")],
    tags: ["car", "charger", "phone", "usb"],
    imageBadge: { text: "Free Gift Inside", style: "gold", icon: "redeem" },
    perk: { text: "Free Air Freshener", icon: "redeem", style: "gold" },
    gift: { name: "Car Vent Air Freshener", value: 2_000, conditions: "One free air freshener with every charger." },
    stock: [45, 30, 160],
    ageDays: 8,
  },
  {
    slug: "ultrasonic-pest-repeller-2pack",
    name: "Ultrasonic Pest & Mosquito Repeller (Pack of 2)",
    category: "home-tech",
    price: 13_500,
    compareAt: 24_000,
    short: "Plug-in ultrasonic repeller for mosquitoes, rats and cockroaches.",
    description: "Silent plug-in units that use ultrasonic waves to keep pests away — no chemicals, no smell, safe around children.",
    images: [img("pest-repeller.webp", "Two ultrasonic pest repeller plug-ins in a clean white home interior")],
    tags: ["mosquito", "pest", "rats", "home"],
    imageBadge: { text: "Pay On Delivery", style: "emerald", icon: "verified" },
    perk: { text: "Lagos Hub Ready", icon: "schedule", style: "neutral" },
    stock: [60, 40, 200],
    ageDays: 50,
  },
  {
    slug: "mini-thermal-printer",
    name: "Portable Mini Thermal Printer for Phone (No Ink Needed)",
    category: "smart-gadgets",
    price: 21_500,
    compareAt: 35_000,
    short: "Print stickers, labels and receipts from your phone — no ink ever.",
    description: "Pocket Bluetooth thermal printer for small businesses and students. Print order labels, receipts, notes and photos straight from your phone.",
    images: [img("thermal-printer.webp", "Pocket thermal printer printing stickers beside a smartphone")],
    tags: ["printer", "bluetooth", "business", "sticker"],
    imageBadge: { text: "3 Rolls Free", style: "gold", icon: "redeem" },
    perk: { text: "Zero Ink System", icon: "check_circle", style: "gold" },
    gift: { name: "3 Thermal Paper Rolls", value: 3_000, conditions: "3 rolls included free with every printer." },
    stock: [20, 15, 70],
    ageDays: 5,
  },
  {
    slug: "100w-braided-multi-cable",
    name: "100W Super Fast Charging Braided Multi-Cable",
    category: "smart-gadgets",
    price: 8_500,
    compareAt: 15_000,
    short: "One braided cable for Type-C, Lightning and Micro devices.",
    description: "Tough nylon-braided 3-in-1 cable rated for 100W fast charging with gold-alloy connectors.",
    images: [img("multi-cable.webp", "Braided 100W multi charging cable with gold connectors on a dark blue background")],
    tags: ["cable", "charger", "usb", "fast charging"],
    imageBadge: { text: "100W Fast Charging", style: "bronze", icon: "bolt" },
    perk: { text: "Universal All-in-1", icon: "verified", style: "neutral" },
    stock: [120, 80, 400],
    ageDays: 90,
  },
  {
    slug: "automatic-water-dispenser-pump",
    name: "Automatic Water Dispenser Pump for Big Bottles",
    category: "kitchen",
    price: 9_500,
    compareAt: 16_000,
    short: "One-touch rechargeable pump for 19/20-litre dispenser bottles.",
    description: "Turn any big water bottle into a dispenser. One button, USB rechargeable, food-grade silicone tube.",
    images: [img("water-pump.webp", "Rechargeable water dispenser pump mounted on a 20 litre bottle")],
    tags: ["water", "pump", "dispenser", "kitchen"],
    imageBadge: { text: "USB Rechargeable", style: "navy", icon: "bolt" },
    perk: { text: "30 Days On 1 Charge", icon: "battery_charging_full", style: "gold" },
    stock: [70, 50, 220],
    ageDays: 30,
  },
  {
    slug: "magnetic-door-window-alarm",
    name: "Magnetic Anti-Theft Door & Window Alarm",
    category: "security",
    price: 12_000,
    compareAt: 20_000,
    short: "120dB siren the moment a door or window opens.",
    description: "Peel-and-stick magnetic sensors with a loud 120dB siren and remote control. Ideal for doors, windows, shops and wardrobes.",
    images: [img("door-alarm.webp", "Magnetic wireless door alarm sensor mounted on a glass door")],
    tags: ["alarm", "security", "door", "window"],
    imageBadge: { text: "120dB Siren", style: "red", icon: "security" },
    perk: { text: "No Drilling Needed", icon: "build", style: "neutral" },
    stock: [40, 30, 120],
    ageDays: 25,
  },
  // ── Extra realistic catalogue ──────────────────────────────────────────────
  { slug: "cordless-tyre-inflator", name: "Portable Digital Tyre Inflator (Cordless)", category: "car-tech", price: 28_500, compareAt: 45_000, short: "Pump tyres to exact PSI anywhere — auto stop.", description: "Rechargeable digital air compressor for car, bike and ball tyres with preset pressure and LED torch.", images: [ph("cordless-tyre-inflator", "Cordless digital tyre inflator")], tags: ["car", "tyre", "pump", "inflator"], perk: { text: "Auto-Stop at Set PSI", icon: "speed", style: "neutral" }, stock: [15, 10, 60], ageDays: 15 },
  { slug: "dual-dash-cam-1080p", name: "1080p Dual Dash Cam with Night Vision", category: "car-tech", price: 32_000, compareAt: 52_000, short: "Front and cabin recording for insurance and peace of mind.", description: "Records the road and cabin in Full HD with loop recording, G-sensor incident lock and night vision.", images: [ph("dual-dash-cam-1080p", "Dual lens dash camera")], tags: ["car", "camera", "dashcam", "security"], stock: [12, 8, 40], ageDays: 3 },
  { slug: "magnetic-car-phone-holder", name: "Magnetic Car Phone Holder (Air Vent)", category: "car-tech", price: 6_500, compareAt: 11_000, short: "One-hand magnetic mount that never drops your phone.", description: "Strong N52 magnets and a 360° ball joint keep your phone steady on Lagos roads.", images: [ph("magnetic-car-phone-holder", "Magnetic air vent phone holder")], tags: ["car", "phone", "holder"], stock: [80, 60, 300], ageDays: 70 },
  { slug: "car-seat-gap-organizer", name: "Car Seat Gap Filler Organizer (Pair)", category: "car-tech", price: 7_500, compareAt: 12_500, short: "Stop phones and coins falling between seats.", description: "Leather gap fillers with storage pockets and a cable pass-through.", images: [ph("car-seat-gap-organizer", "Car seat gap filler organizer")], tags: ["car", "organizer"], stock: [40, 25, 150], ageDays: 45 },
  { slug: "car-jump-starter-12000", name: "12V Car Jump Starter Power Bank 12000mAh", category: "car-tech", price: 45_000, compareAt: 68_000, short: "Start a flat battery without another car.", description: "Compact lithium jump starter for petrol cars up to 4.0L, doubles as a power bank and torch.", images: [ph("car-jump-starter-12000", "Car jump starter power bank")], tags: ["car", "battery", "jump starter", "powerbank"], warrantyMonths: 12, stock: [10, 6, 40], ageDays: 22 },
  { slug: "rechargeable-milk-frother", name: "Rechargeable Milk Frother & Egg Whisk", category: "kitchen", price: 5_500, compareAt: 9_000, short: "Café-style foam and fluffy eggs in seconds.", description: "USB-rechargeable handheld frother with two whisk heads and three speeds.", images: [ph("rechargeable-milk-frother", "Handheld milk frother")], tags: ["kitchen", "whisk", "coffee"], stock: [60, 40, 200], ageDays: 18 },
  { slug: "pull-string-garlic-crusher", name: "Manual Pull-String Garlic & Pepper Crusher", category: "kitchen", price: 4_500, compareAt: 8_000, short: "No electricity needed — pull to chop.", description: "Pull-cord mini chopper for garlic, ginger, pepper and onions. Works during light outs.", images: [ph("pull-string-garlic-crusher", "Pull string garlic crusher")], tags: ["kitchen", "chopper", "manual"], stock: [90, 70, 300], ageDays: 80 },
  { slug: "glass-oil-sprayer", name: "Glass Oil Sprayer Bottle for Air Fryer", category: "kitchen", price: 4_000, compareAt: 7_000, short: "Use less oil, cook healthier.", description: "Fine-mist glass oil sprayer for air fryers, salads and grilling.", images: [ph("glass-oil-sprayer", "Glass oil sprayer bottle")], tags: ["kitchen", "air fryer", "oil"], stock: [70, 50, 250], ageDays: 65 },
  { slug: "mini-food-vacuum-sealer", name: "Mini Food Vacuum Sealer Machine", category: "kitchen", price: 18_500, compareAt: 30_000, short: "Keep meat and fish fresh 5x longer.", description: "Seal bags airtight for freezer storage. Includes 10 starter bags.", images: [ph("mini-food-vacuum-sealer", "Food vacuum sealer machine")], tags: ["kitchen", "storage", "sealer"], stock: [18, 12, 60], ageDays: 10 },
  { slug: "portable-usb-juice-blender", name: "Portable USB Juice Blender 380ml", category: "kitchen", price: 11_000, compareAt: 18_000, short: "Smoothies on the go, charged by USB.", description: "Six stainless blades blend fruit, ice and protein shakes anywhere.", images: [ph("portable-usb-juice-blender", "Portable juice blender bottle")], tags: ["kitchen", "blender", "smoothie", "rechargeable"], stock: [45, 30, 160], ageDays: 28 },
  { slug: "digital-kitchen-scale-10kg", name: "Digital Kitchen Scale 10kg", category: "kitchen", price: 7_000, compareAt: 12_000, short: "Accurate to 1g for baking and small-chops business.", description: "Slim tempered-glass scale with tare function and backlit display.", images: [ph("digital-kitchen-scale-10kg", "Digital kitchen scale")], tags: ["kitchen", "scale", "baking"], stock: [50, 30, 180], ageDays: 55 },
  { slug: "rechargeable-solar-standing-fan", name: "Rechargeable Solar Standing Fan 16-inch", category: "solar-power", price: 58_000, compareAt: 85_000, short: "Cool nights during NEPA outages — 10+ hours per charge.", description: "16-inch standing fan with solar panel, AC charging, LED light and USB output for phones.", images: [ph("rechargeable-solar-standing-fan", "Rechargeable solar standing fan")], tags: ["fan", "solar", "rechargeable", "cooling"], warrantyMonths: 6, stock: [8, 6, 30], ageDays: 14 },
  { slug: "solar-emergency-bulb-3pack", name: "Solar Rechargeable Emergency Bulb (Pack of 3)", category: "solar-power", price: 9_000, compareAt: 15_000, short: "Bulbs that keep shining when light goes off.", description: "Works as a normal bulb and automatically switches to battery during outages. Solar panel included.", images: [ph("solar-emergency-bulb-3pack", "Solar rechargeable emergency bulbs")], tags: ["solar", "bulb", "light", "emergency"], stock: [70, 50, 250], ageDays: 75 },
  { slug: "portable-power-station-300w", name: "300W Portable Power Station", category: "solar-power", price: 185_000, compareAt: 250_000, short: "Run TV, fan, laptop and Wi-Fi through the night.", description: "Pure sine wave lithium power station with AC, DC and USB-C outputs. Charges from solar or wall.", images: [ph("portable-power-station-300w", "Portable power station")], tags: ["solar", "generator", "power", "inverter"], warrantyMonths: 12, stock: [4, 3, 15], ageDays: 6 },
  { slug: "automatic-voltage-protector", name: "Automatic Voltage Protector (AVS) for Fridge", category: "solar-power", price: 12_500, compareAt: 19_000, short: "Protect your fridge and freezer from surges.", description: "Delays restart after outages and cuts off high/low voltage to protect compressors.", images: [ph("automatic-voltage-protector", "Automatic voltage switcher")], tags: ["power", "surge", "fridge", "protector"], stock: [40, 30, 150], ageDays: 100 },
  { slug: "touch-rechargeable-desk-lamp", name: "Touch Control Rechargeable Desk Lamp", category: "solar-power", price: 10_500, compareAt: 17_000, short: "Read and work through power cuts.", description: "Three brightness levels, foldable neck and 8-hour battery.", images: [ph("touch-rechargeable-desk-lamp", "Rechargeable desk lamp")], tags: ["lamp", "rechargeable", "study"], stock: [35, 25, 120], ageDays: 33 },
  { slug: "bluetooth-calling-smart-watch", name: "Bluetooth Calling Smart Watch", category: "smart-gadgets", price: 22_000, compareAt: 38_000, short: "Answer calls, track steps and sleep from your wrist.", description: "1.9-inch display smart watch with Bluetooth calling, heart-rate and 7-day battery.", images: [ph("bluetooth-calling-smart-watch", "Smart watch")], tags: ["watch", "smart", "fitness", "bluetooth"], stock: [25, 20, 90], ageDays: 9 },
  { slug: "enc-wireless-earbuds", name: "Wireless Earbuds with Charging Case (ENC)", category: "smart-gadgets", price: 15_500, compareAt: 26_000, short: "Clear calls even in Lagos traffic.", description: "Environmental noise cancellation mics, touch controls and 24h total battery.", images: [ph("enc-wireless-earbuds", "Wireless earbuds")], tags: ["earbuds", "audio", "bluetooth"], stock: [40, 30, 150], ageDays: 19 },
  { slug: "led-ring-light-tripod", name: "10-inch LED Ring Light with Tripod", category: "smart-gadgets", price: 13_000, compareAt: 22_000, short: "Glow-up lighting for TikTok, Reels and Zoom.", description: "Three colour modes, ten brightness levels and an adjustable tripod with phone holder.", images: [ph("led-ring-light-tripod", "LED ring light with tripod")], tags: ["ring light", "content", "tiktok"], stock: [30, 20, 100], ageDays: 27 },
  { slug: "mini-hd-phone-projector", name: "Mini HD Projector for Phones", category: "smart-gadgets", price: 65_000, compareAt: 95_000, short: "Turn any wall into a 120-inch screen.", description: "Wi-Fi screen mirroring projector with HDMI and USB inputs for movie nights.", images: [ph("mini-hd-phone-projector", "Mini HD projector")], tags: ["projector", "movies", "wifi"], stock: [6, 4, 20], ageDays: 4 },
  { slug: "usb-mosquito-killer-lamp", name: "USB Mosquito Killer Lamp", category: "home-tech", price: 9_800, compareAt: 16_000, short: "Silent UV trap — sleep without bites.", description: "UV light attracts mosquitoes and a quiet fan traps them. No chemicals.", images: [ph("usb-mosquito-killer-lamp", "Mosquito killer lamp")], tags: ["mosquito", "home", "uv"], stock: [55, 40, 200], ageDays: 48 },
  { slug: "rechargeable-lint-remover", name: "Rechargeable Fabric Lint Remover", category: "home-tech", price: 6_000, compareAt: 10_000, short: "Make old clothes look new again.", description: "Removes bobbles and lint from sweaters, suits and upholstery in seconds.", images: [ph("rechargeable-lint-remover", "Fabric lint remover")], tags: ["clothes", "lint", "home"], stock: [60, 45, 200], ageDays: 85 },
  { slug: "motion-sensor-led-strip", name: "Motion Sensor LED Strip Light (Wardrobe)", category: "home-tech", price: 7_500, compareAt: 12_000, short: "Lights up automatically when you open the wardrobe.", description: "Rechargeable magnetic LED bar with motion sensor for wardrobes, kitchens and stairs.", images: [ph("motion-sensor-led-strip", "Motion sensor LED strip light")], tags: ["light", "motion sensor", "wardrobe"], stock: [50, 35, 180], ageDays: 38 },
  { slug: "electric-lunch-box-warmer", name: "Electric Lunch Box Food Warmer", category: "home-tech", price: 14_500, compareAt: 24_000, short: "Hot jollof at the office or in the car.", description: "Plug into a wall socket or car charger to warm your food in 30 minutes.", images: [ph("electric-lunch-box-warmer", "Electric lunch box")], tags: ["lunch box", "food", "warmer", "car"], stock: [30, 20, 110], ageDays: 16 },
  { slug: "wifi-360-security-camera", name: "WiFi Smart Security Camera 360°", category: "security", price: 27_000, compareAt: 45_000, short: "Watch your home live from your phone.", description: "Pan-tilt 1080p camera with night vision, two-way audio and motion alerts.", images: [ph("wifi-360-security-camera", "WiFi security camera")], tags: ["camera", "security", "cctv", "wifi"], stock: [20, 15, 80], ageDays: 7 },
  { slug: "fingerprint-smart-padlock", name: "Fingerprint Smart Padlock", category: "security", price: 12_500, compareAt: 21_000, short: "No more lost keys — unlock with your finger.", description: "Stores up to 20 fingerprints, USB rechargeable, weather resistant.", images: [ph("fingerprint-smart-padlock", "Fingerprint padlock")], tags: ["padlock", "security", "fingerprint"], stock: [30, 20, 100], ageDays: 42 },
  { slug: "steering-wheel-lock", name: "Anti-Theft Steering Wheel Lock", category: "security", price: 16_000, compareAt: 26_000, short: "Visible deterrent that keeps your car where you parked it.", description: "Heavy-duty steel lock that fits most steering wheels, with 3 keys.", images: [ph("steering-wheel-lock", "Steering wheel lock")], tags: ["car", "security", "lock"], stock: [25, 15, 90], ageDays: 58 },
  { slug: "bladeless-neck-fan", name: "Bladeless Hanging Neck Fan", category: "problem-solvers", price: 11_500, compareAt: 19_000, short: "Personal breeze for hot afternoons and traffic.", description: "Hands-free, hair-safe neck fan with three speeds and 8-hour battery.", images: [ph("bladeless-neck-fan", "Bladeless neck fan")], tags: ["fan", "cooling", "portable"], stock: [45, 30, 160], ageDays: 11 },
  { slug: "handheld-garment-steamer", name: "Handheld Garment Steamer", category: "problem-solvers", price: 17_500, compareAt: 28_000, short: "Wrinkle-free clothes in 30 seconds — no ironing board.", description: "Fast-heating travel steamer for shirts, agbada, aso-ebi and curtains.", images: [ph("handheld-garment-steamer", "Handheld garment steamer")], tags: ["steamer", "clothes", "iron"], stock: [25, 20, 90], ageDays: 21 },
  { slug: "electric-spin-scrubber", name: "Electric Spin Scrubber Cleaning Brush", category: "problem-solvers", price: 19_500, compareAt: 32_000, short: "Scrub tiles, sinks and rims without bending.", description: "Cordless spin scrubber with 6 brush heads and extendable handle.", images: [ph("electric-spin-scrubber", "Electric spin scrubber")], tags: ["cleaning", "bathroom", "scrubber"], stock: [20, 15, 80], ageDays: 13 },
  { slug: "waterproof-phone-pouch", name: "Waterproof Phone Pouch (Pack of 2)", category: "problem-solvers", price: 3_500, compareAt: 6_000, short: "Keep your phone dry in rain and on the beach.", description: "IPX8 touch-friendly pouches with lanyard. Fits phones up to 7 inches.", images: [ph("waterproof-phone-pouch", "Waterproof phone pouch")], tags: ["phone", "waterproof", "rain"], stock: [100, 80, 400], ageDays: 95 },
  { slug: "self-wringing-flat-mop", name: "Self-Wringing Flat Mop", category: "problem-solvers", price: 8_000, compareAt: 13_500, short: "Clean floors without touching dirty water.", description: "360° flat mop with built-in squeeze slider and two microfibre pads.", images: [ph("self-wringing-flat-mop", "Self wringing flat mop")], tags: ["mop", "cleaning", "floor"], stock: [35, 25, 120], ageDays: 52 },
];

const DEFAULT_FAQS: SeedFaq[] = [
  { q: "How do I pay?", a: "Place your order on this page, then tap “Complete Payment on WhatsApp”. Our team confirms your order in chat and shares MUBAZZAR's official payment details. Pay on Delivery can be arranged in chat. We never ask for card PINs or OTPs." },
  { q: "How long will delivery take?", a: "Lagos and Abuja orders placed before the daily cut-off can arrive the same day. Other states take 2–4 working days. Your exact fee and delivery time show when you choose your state." },
  { q: "What if it arrives faulty?", a: "Every item is tested before dispatch. If anything is defective, message us within 7 days for a free swap or refund." },
];

export function faqsFor(p: SeedProduct): SeedFaq[] {
  return p.faqs ?? DEFAULT_FAQS;
}

export function featuresFor(p: SeedProduct): SeedFeature[] {
  return (
    p.features ?? [
      { icon: "fact_check", title: "Tested before dispatch", description: "Unboxed and checked by our team in Lagos before it ships to you." },
      { icon: "local_shipping", title: "Fast nationwide delivery", description: "Same-day in Lagos & Abuja before cut-off; 2–4 working days elsewhere." },
      { icon: "currency_exchange", title: "7-day swap guarantee", description: "Faulty on arrival? We replace it free." },
    ]
  );
}
